version: '3.7'
services:
  tomcat: 
    image: tomcat:8.0-alpine
    environment:
      - TOMCAT_USERNAME=admin
      - TOMCAT_PASSWORD=admin
    ports:
      - 8082:8080
    volumes:
      - ./tomcat/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
